### ISSUE TITLE
[Android] folder is missing

### ISSUE THREAD

**Issue by AliRehman7141** [cristianoccazinsp/react-native-background-upload#1]
How can manage two libraries with the same name, your repo didn't contain an android folder? So, I need to use the npm repo for android but for iOS your repo is stable.

**Comment by xHeinrich** [comment]
@cristianoccazinsp also curious how you handle using this for ios and the main package for android.

**Comment by cristianoccazinsp** [comment]
Hi guys,

This is more or less a copy of https://github.com/Vydia/react-native-background-upload, but with improvements and/or changes that we needed that are very specific and could not be merged.

Further, this is an iOS only version of the package, as it is not needed for Android. For Android, use regular requests and foreground services (e.g., https://github.com/cristianoccazinsp/react-native-foreground-service).  Using foreground services will ensure your app stays alive and uploads everything it needs to.

Either way, if you really want to use this for android, just fork this repo and merge the android changes from https://github.com/Vydia/react-native-background-upload.

**Comment by AliRehman7141** [comment]
I'm using this library for ios and library on npm using for android and everything is okay but now I have two separate branches on my code repo.
